name: flutter_text_viewer
description: Flutter textviewer package provide easy way to load text from assets,file and even direct input string and search option.
version: 0.0.1
homepage: https://github.com/CodingWithTashi/flutter_text_viewer
issue_tracker: https://github.com/CodingWithTashi/flutter_text_viewer/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
